In [1]:
a = 10 
b = 20
c= a+b
print(c)

30


In [1]:
a= 10 
b= 20 
c= a*b
print(c)

200


In [ ]:
==================== EDA =================================
1) pandas            : Dataframe or data applications
2) numpy             : Numerical python for math operations
3) matplotlib        : For plots graphs
4) Seaborn           : For plots graphs
5) Bokhe             : For plots
6) plotly            : For plots

================= Machine learning ===========================
7) Scikit learn(Sklearn)  :  ML models
8) stats                  :  statistical models 

=================== Data retrival from sql scrapping ==================
9) Sqlite                : connect with database
10) Beautiful soup       : scrap the data from website
11) websocket            : scrap

=================== Deep learning/ computer vision ==================================
12) Tensorflow           :  Google
13) Keras                :  DL models
14) OpenCV               : Image opeartions             
15) Pillow (PIL)         : Image operations
16) Pytorch              : Facebook
17) Pretrained model
     VGG16
     Mobilenet
     RESNET
     RCNN
     MASKRCNN
     FASTERCNN
     YOLO
====================== Natural language process ============
18) NLTK               : natural language process
19) Scipy
20) Word2vec (How words will convert into vector) : 
21) GloVE    
22) Wordcloud

================== Hugging face =========================
23) Transformers    : BERT

==================== GenAI models ========================
24) OpenAI+Microsoft : GPT Models
25) Google           : Gemini
26) Amazon           : Q
27) Meta Facebook    : MetaAI
28) Apple 

LLAMA 
GEMMA
Dalle-E
T5

ALL ARE HAVING DIFFERENT DIFFERENT PACKAGES

==================== LANGCHAIN ====================
29) LangChain Framework
================ Deployments/applications ====================
30) Flask
31) Streamlit
32) Django

================ MLops =====================================
33) Mlflow
34) Kubeflow
35) Azure Ai services : azure packages
36) GCP :  GCP packages

**Step-1** 

**Create a Dataframe**

- we will create a dataframe using list

- we will create a dataframe using dictionary

In [1]:
import pandas as pd

In [3]:
d1=pd.DataFrame()
d1

Empty DataFrame
Columns: []
Index: []

In [4]:
type(d1)

pandas.core.frame.DataFrame

**Step-2**

**Provide the data**

In [5]:
names=['tarun','surendar','mohith']
pd.DataFrame(names)

0
0     tarun
1  surendar
2    mohith

In [6]:
names=['tarun','surendar','mohith']
age=[20,21,22]
data=zip(names,age)
pd.DataFrame(data)

0   1
0     tarun  20
1  surendar  21
2    mohith  22

In [8]:
names=['tarun','surendar','mohith']
age=[20,21,22]
city=['Hyd','ECIL','Blr']
pd.DataFrame(zip(names,age,city))

0   1     2
0     tarun  20   Hyd
1  surendar  21  ECIL
2    mohith  22   Blr

**Step-3**
**Provide the column names**

In [9]:
names=['tarun','surendar','mohith']
pd.DataFrame(names, 
             columns=['Names'])

Names
0     tarun
1  surendar
2    mohith

In [10]:
names=['tarun','surendar','mohith']
age=[20,21,22]
pd.DataFrame(zip(names,age),
            columns=['Names','Age'])

Names  Age
0     tarun   20
1  surendar   21
2    mohith   22

In [11]:
names=['tarun','surendar','mohith']
age=[20,21,22]
city=['Hyd','ECIL','Blr']

data=zip(names,age,city)

cols=['Names','Age','City']

pd.DataFrame(data,columns=cols)

Names  Age  City
0     tarun   20   Hyd
1  surendar   21  ECIL
2    mohith   22   Blr

**Step-4**

**Providing index**

In [12]:
names=['tarun','surendar','mohith']
age=[20,21,22]
city=['Hyd','ECIL','Blr']

data=zip(names,age,city)
ix=['A','B','C']  # 3 rows we need 3 index
cols=['Names','Age','City'] # 3 columns , 3 values

pd.DataFrame(data,
             index=ix,
             columns=cols)

Names  Age  City
A     tarun   20   Hyd
B  surendar   21  ECIL
C    mohith   22   Blr

In [ ]:
names=['tarun','surendar','mohith']
pd.DataFrame(names)

names=['tarun','surendar','mohith']
pd.DataFrame(names, 
             columns=['Names'])
# Why names is passing in list format if we have 1 column only--
##################################################################
names=['tarun','surendar','mohith']
age=[20,21,22]
pd.DataFrame(zip(names,age),
            columns=['Names','Age'])
#############################################
names=['tarun','surendar','mohith']
age=[20,21,22]
city=['Hyd','ECIL','Blr']

data=zip(names,age,city)

cols=['Names','Age','City']

pd.DataFrame(data,columns=cols)

In [14]:
name = ['Tarun', 'Venkat', 'Sahasra']
age = [20, 35, 12]
city = ['Hyd', 'Blr', 'Chn']
data = zip(name, age)
column=['Name', 'Age']
df=pd.DataFrame(data, index=city, columns=column)

In [15]:
df

Name  Age
Hyd    Tarun   20
Blr   Venkat   35
Chn  Sahasra   12

- create a dataframe

- provide the data

- add the columns

- provide the column names

- provide the index

In [ ]:
import pandas as pd

In [1]:
pd.DataFrame()

NameError: name 'pd' is not defined

**Step-5**

**Add a new column on existing data frame**

In [4]:
# Create a dataframe
# Name
# age 
# city

import pandas as pd
names=['tarun','surendar','mohith']
age=[20,21,22]
city=['Hyd','ECIL','Blr']

data=zip(names,age,city)

cols=['Names','Age','City']

df=pd.DataFrame(data,columns=cols)
df

Names  Age  City
0     tarun   20   Hyd
1  surendar   21  ECIL
2    mohith   22   Blr

- If you want to add a new column 

- First check how many rows are there

- For example in above dataframe we have 3 rows

- your new column also should have 3 rows

- suppose I want to create a new column: **salary**

- make a list with 3 values

- salary=[100000,200000,300000]

**syntax**:  dataframe[column]=list of values

- salary=[100000,200000,300000]

- df['salary']=salary`

In [5]:
df['salary']=[]

ValueError: Length of values (0) does not match length of index (3)

In [6]:
salary=[10000,20000,30000]
df['Salary']=salary
df

Names  Age  City  Salary
0     tarun   20   Hyd   10000
1  surendar   21  ECIL   20000
2    mohith   22   Blr   30000

**use case-1**

- Create empty data frame first

- Create 3 list  using list comprehension

- list1= a values from 1 to 10 

- list2= square of  1 to  10

- list3= cube of 1 to 10

- Finally make a dataframe

In [8]:
import pandas as pd
df1=pd.DataFrame()
df1

Empty DataFrame
Columns: []
Index: []

In [12]:
l1=[i for i in range(1,10)]
l2=[i**2 for i in range(1,10)]
l3=[i**3 for i in range(1,10)]
df1['X']=l1
df1['Y']=l2 
df1['Z']=l3
df1

X   Y    Z
0  1   1    1
1  2   4    8
2  3   9   27
3  4  16   64
4  5  25  125
5  6  36  216
6  7  49  343
7  8  64  512
8  9  81  729

**Step-6**

**Update the already existed column**

- Create a new column

    - createing a new list  salary=[1000,2000,3000]

    - df['S']

    - Creating a new column the column name is our choice

- update existing coumn are same way only

    - Here also we need a make a list of values = number of rows

    - while updating the existing column

    - we need to provide already existed column name only

    - df['Z']= list of values

In [13]:
# dataframe name: df1
# list of values variable name: z
# which column we want to update : Z'
z=[i**4 for i in range(1,10)]
df1['Z']=z
df1

X   Y     Z
0  1   1     1
1  2   4    16
2  3   9    81
3  4  16   256
4  5  25   625
5  6  36  1296
6  7  49  2401
7  8  64  4096
8  9  81  6561

In [16]:
df2=pd.DataFrame()
l1=[i for i in range(1,10)]                     # use list comprehension to create the list
l2=[i**2 for i in range(1,10)]                    # use list comprehension to create the list
l3=[i**3 for i in range(1,10)]                 # use list comprehension to create the list

df2['Number']=l1                                   # create column headings X,Y,Z
df2['Square']=l2
df2['Cube']=l3

df2

Number  Square  Cube
0       1       1     1
1       2       4     8
2       3       9    27
3       4      16    64
4       5      25   125
5       6      36   216
6       7      49   343
7       8      64   512
8       9      81   729

**Step-7**

**Drop the column**

In [18]:
# How to check the columns
df1.columns

Index(['X', 'Y', 'Z', 'Number', 'Square', 'Cube'], dtype='object')

- If you want to drop a specific column

- we will use drop method

- we already know about difference between keywords and methods

- Keywords will use directly

- Methods will use with corresponding dataframe

- **Method name: drop**

**df1.drop()**

- Column: which column you want to drop

- axis:  Represents the specified value is a row or column

    - axis= 0 means rows

    - axis=1 means column
 
    - by default axis=0

- inplace: will provide overwrite the dataframe or not

    - inplace= True , this indicates overwrite the dataframe

    - inplace=False, this indicates the modified dataframe will be use when you provide
      new variable for the operation

In [19]:
df1.drop('X')  
# we are not providing axis
# it assuming the provided value is  a row
# by default axis=0  ==== rows

KeyError: "['X'] not found in axis"

In [20]:
df1.drop('X',axis=1)

# after this in a new cell type df1
# you will see original dataframe
# because we did not provide inplace

# If you want to use below output
# you need to assign a variable
#df_new=df1.drop('X',axis=1)

Y     Z  Number  Square  Cube
0   1     1       1       1     1
1   4    16       2       4     8
2   9    81       3       9    27
3  16   256       4      16    64
4  25   625       5      25   125
5  36  1296       6      36   216
6  49  2401       7      49   343
7  64  4096       8      64   512
8  81  6561       9      81   729

In [21]:
df1.drop('X',axis=1,inplace=True)
df1

Y     Z  Number  Square  Cube
0   1     1       1       1     1
1   4    16       2       4     8
2   9    81       3       9    27
3  16   256       4      16    64
4  25   625       5      25   125
5  36  1296       6      36   216
6  49  2401       7      49   343
7  64  4096       8      64   512
8  81  6561       9      81   729

In [ ]:
# Read the data frame
# Provide the data
# Provide the column names
# Change the index
# Add the new column
# Modify the existing column
# Drop the column
#      axis   inplace
# You need to create a new column
# Drop the old column

**Step-8**

**drop the row**

- drop the column and drop the rows both are similar only

- the only difference is axis 

    - axis= 0  represnts rows 

    - by default axis=0 available 

    - which means if we provide any value, it will represnt rows only

In [3]:
# Dataframe name: df1
import pandas as pd
df2=pd.DataFrame()
l1=[i for i in range(1,10)]                     
l2=[i**2 for i in range(1,10)]                    
l3=[i**3 for i in range(1,10)]                 

df2['Number']=l1                                  
df2['Square']=l2
df2['Cube']=l3

df2

Number  Square  Cube
0       1       1     1
1       2       4     8
2       3       9    27
3       4      16    64
4       5      25   125
5       6      36   216
6       7      49   343
7       8      64   512
8       9      81   729

In [6]:
df2.drop(4)
# If we run this we will get error
# by default axis=0 which represents about rows
# But 'Number'  is  a column
# If you want to drop row, the provide the row index

Number  Square  Cube
0       1       1     1
1       2       4     8
2       3       9    27
3       4      16    64
5       6      36   216
6       7      49   343
7       8      64   512

In [7]:
# Multiple rows
# Multiple columns keep always in a list
df2.drop([4,8])

Number  Square  Cube
0       1       1     1
1       2       4     8
2       3       9    27
3       4      16    64
5       6      36   216
6       7      49   343
7       8      64   512

In [16]:
df2.columns[[0,1]]

Index(['Number', 'Square'], dtype='object')

In [12]:
df2.drop([0,1],axis=1)
# [0,1]  index
# axis=1  columns
# error

KeyError: '[0, 1] not found in axis'

**Step-9**

**How to select the column**

In [21]:
df2['Square']

# Series type
# No column name display
# Whenever you see this type : Series type

0     1
1     4
2     9
3    16
4    25
5    36
6    49
7    64
8    81
Name: Square, dtype: int64

In [22]:
df2[['Square']]
# Data frame

Square
0       1
1       4
2       9
3      16
4      25
5      36
6      49
7      64
8      81

In [23]:
type(df2['Number'])

pandas.core.series.Series

In [24]:
type(df2[['Number']])

pandas.core.frame.DataFrame

In [25]:
df2.Number

0    1
1    2
2    3
3    4
4    5
5    6
6    7
7    8
8    9
Name: Number, dtype: int64

- df2['Number']: Series type

- df2[['Number']] :  Dataframe type

- df2.Number : Series type


In [26]:
cols=['Number','Square']
df2[cols]

Number  Square
0       1       1
1       2       4
2       3       9
3       4      16
4       5      25
5       6      36
6       7      49
7       8      64
8       9      81

In [27]:
df2['Number'].values

array([1, 2, 3, 4, 5, 6, 7, 8, 9], dtype=int64)

- All values comes in an array

- Array means it is a list of elements only represnts using numpy pacakge

- Generally elements present in 4 ways

    - List : Basic represntations

    - Numpy array : Array  with Numpy package 

    - Tensors : Tensorflow package

    - Torch   : Pytorch package

In [28]:
list1=[1,2,3,4]
list1

[1, 2, 3, 4]

In [30]:
import numpy as np
np.array(list1)

array([1, 2, 3, 4])

In [ ]:
#tensor([1,2,3,4])

In [31]:
list1=[1,2,3,4]
list2=[10,20,30,40]
list1+list2

[1, 2, 3, 4, 10, 20, 30, 40]

In [32]:
l1=np.array(list1)
l2=np.array(list2)
l1+l2

array([11, 22, 33, 44])

In [ ]:
# 3 days every day one hour numpy 
# A new package in the market : numpy
# you know python
# 

# Sir what happend about Azure AI certification  : August will start
# Offline 


In [34]:
df2['Number'].values
# Imagine we worked on an ML problem
# We got some series of values
# With that series of values also we can create a datagframe 

array([1, 2, 3, 4, 5, 6, 7, 8, 9], dtype=int64)

In [35]:
df2['NUMBER']=df2['Number'].values
df2

Number  Square  Cube  NUMBER
0       1       1     1       1
1       2       4     8       2
2       3       9    27       3
3       4      16    64       4
4       5      25   125       5
5       6      36   216       6
6       7      49   343       7
7       8      64   512       8
8       9      81   729       9

**Step-10**

**Save the dataframe**

- Dataframes we can save in two formats

    - csv : comma seperated value

    - xlsx : excel format

- In order to save any data

    - Where you want to save : directory name

    - what is the name of the file for storing

    - what is the extension

- we already seen same in file handling session


In [ ]:
#Case-1: Saving file at same location where this python file
# import os
# os.getcwd()
# No need to provide directory path
# Directly give only name of the file
# and extension

In [36]:
# Dataframe name: df2
df2.to_csv('Data1.csv')
df2.to_excel('Data1.xlsx')

**Step-11**
**How to read a dataframe**

In [37]:
import pandas as pd
pd.read_csv('Data1.csv')

Unnamed: 0  Number  Square  Cube  NUMBER
0           0       1       1     1       1
1           1       2       4     8       2
2           2       3       9    27       3
3           3       4      16    64       4
4           4       5      25   125       5
5           5       6      36   216       6
6           6       7      49   343       7
7           7       8      64   512       8
8           8       9      81   729       9

In [38]:
import os
os.getcwd()

'C:\\Users\\omkar\\OneDrive\\Documents\\Data science\\Naresh IT\\Naresh IT\\Data science\\Batches\\Batch-8_May\\EDA'

In [39]:
import pandas as pd
pd.read_excel('Data1.xlsx')

Unnamed: 0  Number  Square  Cube  NUMBER
0           0       1       1     1       1
1           1       2       4     8       2
2           2       3       9    27       3
3           3       4      16    64       4
4           4       5      25   125       5
5           5       6      36   216       6
6           6       7      49   343       7
7           7       8      64   512       8
8           8       9      81   729       9

**Step-12:**

**How to avoid index column**

- while we save the dataframe

- automatically a new column will create

- that we need to avoid

- Permission denied means close the data file from laptop

In [41]:
# Dataframe name: df2
# save the data with out index column
df2.to_csv('Data1.csv',index=False)
df2.to_excel('Data1.xlsx',index=False)

In [42]:
# read the data
import pandas as pd
pd.read_csv('Data1.csv')

Number  Square  Cube  NUMBER
0       1       1     1       1
1       2       4     8       2
2       3       9    27       3
3       4      16    64       4
4       5      25   125       5
5       6      36   216       6
6       7      49   343       7
7       8      64   512       8
8       9      81   729       9